import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Web3 Tontine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-auto max-w-7xl max-h-screen">
        <h1 className="text-4xl font-bold text-indigo-700 font-Tapestry">
          A Tontine Web 3 App 
        </h1>

        <p className="">
          Description of the project
        </p>

      </main>

    </>
  )
}

export default Home
